#pragma once

#ifdef RGBLIGHT_ENABLE

    #undef RGBLIGHT_LED_COUNT
    #define RGBLIGHT_LED_COUNT 12

    #define RGBLIGHT_EFFECT_BREATHING
    #define RGBLIGHT_EFFECT_RAINBOW_MOOD
    #define RGBLIGHT_EFFECT_SNAKE

    #undef RGBLIGHT_SPLIT
    #define RGBLIGHT_SPLIT { 6, 6 }

    #undef RGBLIGHT_LIMIT_VAL
    #define RGBLIGHT_LIMIT_VAL 255
#endif

